services:
  postgres:
    image: docker.arvancloud.ir/postgres:17
    container_name: container-name
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d online_shop_db"]
      interval: 5s
      timeout: 5s
      retries: 10
  redis:
    image: docker.arvancloud.ir/redis:7-alpine
    container_name: cont_name
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: cont_name
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    environment:
      POSTGRES_HOST: test
      POSTGRES_PORT: 5432
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
